### ISSUE TITLE
在Mohist服务器上运行DrinkIt崩溃

### ISSUE THREAD

**Issue by Dark2932** [Nova-Committee/DrinkIt#4]
**版本Minecraft 1.12.2，Mohist-300**
**mods文件夹中只有一个文件，但它提示我重复了，不知道是什么原因**
**我尝试更换了自带mixin的版本，但依旧会崩溃，且报错一模一样**
## 报错如下

崩溃时间: 23-1-5 下午9:45
描述: 服务器在进行tick循环时发生异常 (Exception in server tick loop)

Duplicate Mods:
	drinkit : G:\Minecraft\lobby\.\mods\DrinkIt-Forge-1.12.2-1.0.0-mixinless.jar
	drinkit : G:\Minecraft\lobby\.\mods\DrinkIt-Forge-1.12.2-1.0.0-mixinless.jar

net.minecraftforge.fml.common.DuplicateModsFoundException
	at net.minecraftforge.fml.common.Loader.identifyDuplicates(Loader.java:482)
	at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:444)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:583)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:101)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:331)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:167)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:590)
	at java.lang.Thread.run(Thread.java:750)

No Mixin Metadata is found in the Stacktrace.

**Comment by VulpesStella** [comment]
把模组删除试试

**Comment by Dark2932** [comment]
> 把模组删除试试

删除了用啥啊（）

**Comment by VulpesStella** [comment]
我的意思是先排除一下有没有一个“被隐藏”的文件

**Comment by Dark2932** [comment]
> 我的意思是先排除一下有没有一个“被隐藏”的文件

已检查并测试，并不是该问题。
